
name: Long to Short

# Controls when the workflow will run
on: [workflow_dispatch]

jobs:
  build:
    name: Long to Short
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Start program
        run: |
          sed -i 's/\r//' diftest2.sh
          python3 longtoshort.py sortme.txt
